### ISSUE TITLE
FloatContextMenu throws error in Nuxt 3

### ISSUE THREAD

**Issue by BayBreezy** [ycs77/headlessui-float#69]
**Use Version**
Use version when bugs appear:
 - Headless UI: v1.7.14
 - [Nuxt Headless UI](https://github.com/P4sca1/nuxt-headlessui)
 - Headless UI Float(Vue): v1.1.4
 - Framework: NuxtJS
 - Browser Chrome

**Describe the bug**
I get an error on the browser that says "Node is not defined".
This only happens when i try to use the `FloatContextMenu` component.
Below are the logs:

```bash
500
Node is not defined

at ReactiveEffect.fn (./node_modules/@headlessui-float/vue/dist/headlessui-float.mjs:468:11)
at ReactiveEffect.run (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:162:19)
at ComputedRefImpl.get value [as value] (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:1143:33)
at P (./node_modules/@headlessui-float/vue/dist/headlessui-float.mjs:480:7)
at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:156:18)
at callWithAsyncErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:164:17)
at ReactiveEffect.job [as scheduler] (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:1752:9)
at triggerEffect (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:373:15)
at triggerEffects (./node_modules/@vue/reactivity/dist/reactivity.cjs.js:363:7)
```

In the VSCode terminal, I also get this:
`[Vue warn]: provide() can only be used inside setup().`

**To Reproduce**
Here is the code used that caused the error:

```vue
<template>
  <div class="container py-5">
    <div ref="vl" class="w-full bg-gray-200 rounded-lg h-52">
      <FloatContextMenu v-slot="{ close }" :z-index="999">
        <HeadlessMenu>
          <HeadlessMenuItems
            static
            class="w-48 bg-white border border-gray-200 rounded-md shadow-lg overflow-hidden focus:outline-none"
          >
            <HeadlessMenuItem v-slot="{ active }">
              <button
                type="button"
                class="block w-full px-4 py-1.5 text-left text-sm"
                :class="{ 'bg-indigo-500 text-white': active }"
                @click="close"
              >
                Edit
              </button>
            </HeadlessMenuItem>
            <HeadlessMenuItem v-slot="{ active }">
              <button
                type="button"
                class="block w-full px-4 py-1.5 text-left text-sm"
                :class="{ 'bg-indigo-500 text-white': active }"
                @click="close"
              >
                Cut
              </button>
            </HeadlessMenuItem>
            <div class="my-1 border-b border-gray-100" />
            <HeadlessMenuItem v-slot="{ active }">
              <button
                type="button"
                class="block w-full px-4 py-1.5 text-left text-sm"
                :class="{ 'bg-indigo-500 text-white': active }"
                @click="close"
              >
                Other
              </button>
            </HeadlessMenuItem>
          </HeadlessMenuItems>
        </HeadlessMenu>
      </FloatContextMenu>
    </div>
  </div>
</template>

<script setup lang="ts">
  import { FloatContextMenu } from "@headlessui-float/vue";

  const vl = ref<HTMLElement | null>(null);
</script>
```

**Screenshots**
Browser:
<img width="1305" alt="image" src="https://github.com/ycs77/headlessui-float/assets/53905713/334a105b-d94a-454e-8ef0-ede457fcb761">

**Expected behavior**
I expected the context menu to work as normal

**Comment by gustojs** [comment]
You can mitigate it by wrapping `<FloatContextMenu />` with `<ClientOnly />`.

**Comment by BayBreezy** [comment]
OMG... How did I not try this. Thank you @gustojs 
This worked. Closing this one
